"""Updated message model with sender_id for consistency

Revision ID: af0c53823332
Revises: a6a1acd7b457
Create Date: 2025-05-28 15:27:28.352788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af0c53823332'
down_revision = 'a6a1acd7b457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['last_message_sender_id'], ['id'])
        batch_op.drop_column('reciever_id')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reciever_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
